### ISSUE TITLE
Mac OS X back back button

### ISSUE THREAD

**Issue by enderax** [gabemarshall/Brosec#10]
Hi, 
Is there a way to 'back' to main menu for Mac OS X(El capitan)? Delete or FN + Delete is not working.

**Comment by gabemarshall** [comment]
Hi @enderax , thanks for trying out Brosec! You should be able to navigate the menu by typing `back` (all commands rely on user input). I'm working on some better documentation that will hopefully help explain how to use Brosec.

**Comment by enderax** [comment]
Ah Thank you @gabemarshall . More easier now
