### ISSUE TITLE
Feature: Add basic upload functionality to bros http

### ISSUE THREAD

**Issue by doyler** [gabemarshall/Brosec#14]
I notice that HTTP is occasionally the only (easy) outgoing method that I have on some engagements. It would be nice if the bros http server supported a very basic multipart/form-data with file picking functionality for exfiltration purposes.

While this isn't supported out of the box by SimpleHTTPServer by default, here is an example - https://gist.github.com/3346170

Node specific references:
https://howtonode.org/really-simple-file-uploads
https://github.com/expressjs/multer

**Comment by gabemarshall** [comment]
Thank you! Great idea.

**Comment by gabemarshall** [comment]
Thanks again, /upload now exists in bros v1.2.0
