### ISSUE TITLE
[feature] msfvenom payloads?

### ISSUE THREAD

**Issue by mrpinghe** [gabemarshall/Brosec#20]
Wonderful utility! 10/10!

If you are up to it, maybe consider adding metasploit payloads as well? http://netsec.ws/?p=331 

If not, close this issue as you like

Cheers!

**Comment by gabemarshall** [comment]
Thank you! I do think this would be a useful addition. Let me think about it for a bit and try to decide on what section it should go under.

Initially I'm thinking either as a subsection under "Misc" or having a standalone "Metasploit" section.

**Comment by gabemarshall** [comment]
Added a few to <code>bros 53</code> thats now in master. Thanks again for the suggestion!
