### ISSUE TITLE
Linux, output does not get copied in clipboard

### ISSUE THREAD

**Issue by cegi** [gabemarshall/Brosec#26]
Using latest debian testing, brosec does not copy the output in clipboard, so i have to select it myself and copy it each time. Thats how it goes : 

```
`4. Obtain a TTY via Python

 => python -c 'import pty;pty.spawn("/bin/bash")'



Choose a payload: (1-4) or enter "back" to return to the main menu: 4
python -c 'import pty;pty.spawn("/bin/bash")'`
```

So it just write it in terminal after i choose it, instead of copying it.

**Comment by gabemarshall** [comment]
Hi, thanks for the report. Can you confirm that you have `xsel` installed as mentioned in the install instructions? If you do and it still isn't copying, I'll dig into it further.

Thanks!

**Comment by cegi** [comment]
No i really thought i had it installed, it was the only thing i missed... Thanks problem solved

**Comment by gabemarshall** [comment]
No problem @cegi - I'm working on the next version of Brosec and maybe I can add in some type of notification if xsel is missing. Thanks!
