### ISSUE TITLE
Opening netcat listener doesn't default to yes

### ISSUE THREAD

**Issue by claytondorsey** [gabemarshall/Brosec#5]
When prompted to open a netcat listener with text "(Y/n)" hitting enter doesn't seem to default to yes, despite prompt saying so with the capital Y convention.

```
Choose a payload: (1-5) or enter "back" to return to the main menu:  1
Enter the type of shell to use (/bin/sh, cmd.exe, etc: ::  /bin/sh/
Should I start a netcat listener for you? (Y/n) :: ::
```

**Comment by gabemarshall** [comment]
Thanks for catching this.. should be a quick fix.

Cheers
