### ISSUE TITLE
What about the working procedure?

### ISSUE THREAD

**Issue by beeprime** [gabemarshall/Brosec#8]
After it emits -"Output copied to clipboard", what is the the next step? I have set RHOST, RPORT, LHOST, LPORT, USER and PATH but failed to understand how these can be useful to attack the remote IP?

**Comment by gabemarshall** [comment]
Brosec is a reference/helper utility and does not provide any type of automated attack features. The payloads it generates are intended to be manually used against applications that you're actively pentesting.
